spring:
    profiles:
        active: a
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/userinfo?serverTimezone=Asia/Shanghai
        username: root
        password: root
    thymeleaf:
        cache: false
        check-template: false
        check-template-location: false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    output:
        ansi:
            enabled: detect
    session:
        store-type: redis
        timeout: 3600s
        redis:
            flush-mode: on_save
            namespace: spring:session
    redis:
        host: localhost
        port: 6379
logging:
    config: classpath:logback-spring.xml
    file: myLog.log
server:
    port: 8080
